### ISSUE TITLE
Error after download "pwd: No such file or directory - getcwd"

### ISSUE THREAD

**Issue by Kylmakalle** [sinoru/actions-setup-xcode#1]
Example action file
https://github.com/Kylmakalle/kotatogram-desktop/blob/9352101db3758c17c3aec10a7b092cb99bb47024/.github/workflows/build-macos.yml

```
%/usr/local/lib/ruby/gems/2.6.0/gems/xcode-install-2.6.3/lib/xcode/install.rb:222:in `pwd': No such file or directory - getcwd (Errno::ENOENT)
	from /usr/local/lib/ruby/gems/2.6.0/gems/xcode-install-2.6.3/lib/xcode/install.rb:222:in `install_dmg'
	from /usr/local/lib/ruby/gems/2.6.0/gems/xcode-install-2.6.3/lib/xcode/install.rb:284:in `install_version'
	from /usr/local/lib/ruby/gems/2.6.0/gems/xcode-install-2.6.3/lib/xcode/install/install.rb:50:in `run'
	from /usr/local/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
	from /usr/local/lib/ruby/gems/2.6.0/gems/xcode-install-2.6.3/bin/xcversion:12:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.6.0/bin/xcversion:23:in `load'
	from /usr/local/lib/ruby/gems/2.6.0/bin/xcversion:23:in `<main>'
##[error]The process 'xcversion' failed with exit code 1
##[error]Node run failed with exit code 1
```

**Comment by sinoru** [comment]
I'm looking in to it.

**Comment by sinoru** [comment]
@Kylmakalle I just releases v1.1.1 for fixes related issue. Could you try again?

**Comment by Kylmakalle** [comment]
Thank you for fast update
![image](https://user-images.githubusercontent.com/24507532/69728540-ab1d8980-1135-11ea-97bf-0c14a2c305bb.png)
